name: 02 - Workflow events

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "I have been triggered by a(n) ${{ github.event_name }} event"