name: 03 Workflow runners

on: 
  # push:
  workflow_dispatch:

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: show OS
              run: |
                    echo "This job is running on Ubuntu runner"
                    echo "Runner OS: ${{ runner.os }}"