name: 04-using-actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            - name: Printing folders
              run: |
                    echo "Printing folders in the repository"
                    ls
            - name: setup node
              uses: actions/setup-node@v3
              with:
                node-version: 24
            - name: install dependencies
              run:  npm ci
              working-directory: 04-using-actions/react-app

        # checkout the repository
        # Install deps of our react application
        # execute automate tests
