name: 13 - using caching

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: Whether to use caching or not
                type: boolean
                default: true
            node-version:
                description: Node.js version to use
                type: choice
                options:
                    - 20.x
                    - 21.x
                    - 24.x
                default: 20.x

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .github/13-caching/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: check repository files
              run: |
                pwd
                ls -la
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ inputs.node-version }}
            - name: Download cached dependencies
              if: ${{ inputs.use-cache }}
              uses: actions/cache@v3
              id: cache
              with:
                path: .github/13-caching/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
            - name: Install dependencies
              if: ${{ inputs.use-cache && steps.cache.outputs.cache-hit != 'true' }}
              run: |
                npm install && npm ci
            - name: testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploy to non prod
              run: echo "Deploying to non prod environment"
